### ISSUE TITLE
Spurious errors for openid login

### ISSUE THREAD

**Issue by pchengi** [ESGF/esgf-test-suite#16]
The openid login seems to fail without any reason. Sometimes, it goes through. I'm able to login manually with the same openid and password from the browser, manually. 
![error](https://user-images.githubusercontent.com/3603875/36231398-2e09423e-11de-11e8-896b-7f1c00279203.png)
![error2](https://user-images.githubusercontent.com/3603875/36231399-2e28fec6-11de-11e8-84ef-2fbe912bf7f4.png)

**Comment by pchengi** [comment]
Commandline

pchengi@thebeast:~/esgf-test-suite$ nosetests -v --nocapture --nologcapture --tc-file esg-idx.ini esgf-test-suite/utils esgf-test-suite/test/test_node_components/test_data/test_dl.py
test_dl.TestDataDownload.test_0_http_browser_download ... ERROR
test_dl.TestDataDownload.test_1_globus_url_copy ... ERROR

======================================================================
ERROR: test_dl.TestDataDownload.test_0_http_browser_download
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pchengi/localpython/virtual/python/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/pchengi/esgf-test-suite/esgf-test-suite/test/test_node_components/test_data/test_dl.py", line 68, in test_0_http_browser_download
    globals.browser.find_by_id('password').fill(self.password)
  File "/home/pchengi/localpython/virtual/python/lib/python2.7/site-packages/splinter/element_list.py", line 75, in __getattr__
    self.__class__.__name__, name))
AttributeError: 'ElementList' object has no attribute 'fill'

======================================================================
ERROR: test_dl.TestDataDownload.test_1_globus_url_copy
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pchengi/localpython/virtual/python/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/pchengi/esgf-test-suite/esgf-test-suite/test/test_node_components/test_data/test_dl.py", line 93, in test_1_globus_url_copy
    process = subprocess.Popen(command)
  File "/home/pchengi/localpython/python/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/home/pchengi/localpython/python/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

----------------------------------------------------------------------
Ran 2 tests in 3.004s

**Comment by SebastienGardoll** [comment]
Hi,

Since I fixed issues with the last release (v2.2),  which version did you try ? 
FYI: git checkout ony tags not branches.

**Comment by SebastienGardoll** [comment]
Should be fixed in the 2.3a1 . Reopen if required.
